### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by tonyday567** [tonyday567/numhask-array#13]
https://github.com/tonyday567/numhask-bench

I'm pretty happy with the test harness.

Not so happy that hmatrix is 500 times faster with matrix multiplication.  hehe

**Comment by o1lo01ol1o** [comment]
yeah, i saw that coming.  in the next couple weeks I hope to have some accelerate modules written.  potentially tensor-flow as well depending on how much time I get.

test harness does look legit.  👍

**Comment by o1lo01ol1o** [comment]
I've done some work on an accelerate backend to the api but didn't notice that it's not straight forward to implement `functor` instances on accelerate types.  [See here](https://github.com/AccelerateHS/accelerate/issues/397) . We could reimplement the whole distributive - naperian hierarchy using a constrained category but then I'm not exactly sure how the numhask tower will map onto that.  What do you think?

**Comment by tonyday567** [comment]
I don't know too much about accelerate - time to find out!  But that might take a while.

subhask went the constrained category/sub-category route, and it was all felt well and good at first, but then you looked back at the amount of compatibility work that needed to be done, and then saw how fast haskell practices evolve, you pretty quickly start to miss haskell too much for the neatness to be worthwhile.

So my instinct is to stick with plain categories.  Would [mono-traversable](https://hackage.haskell.org/package/mono-traversable-1.0.4.0/docs/Data-MonoTraversable.html) help?

Let me see if I can get an accelerate instance up and running, and hack it around.

**Comment by o1lo01ol1o** [comment]
work in progress here: https://github.com/o1lo01ol1o/numhask-array/blob/Acclerate/src/NumHask/Accelerate.hs

**Comment by tmcdonell** [comment]
You may be interested in [accelerate-blas](http://hackage.haskell.org/package/accelerate-blas), which has FFI bindings for matrix multiply (and not much else at the moment, but eventually...).

**Comment by tonyday567** [comment]
See #15

**Comment by tonyday567** [comment]
Will deal with performnace in numhask-bench, so closing.
