### ISSUE TITLE
Dimensions experiment

### ISSUE THREAD

**Issue by tonyday567** [tonyday567/numhask-array#18]
Can we use the dimensions library for the type shape stuff?  Should we?

**Comment by o1lo01ol1o** [comment]
Oh, sweet, I hadn't seen that.  Yeah, all we'd need to do is modify the `Nat2Shape` family and we'd be good to go.

**Comment by o1lo01ol1o** [comment]
for reference: replace existing type-level shape functionality with https://hackage.haskell.org/package/dimensions .

**Comment by tonyday567** [comment]
#20 provides
